packages:
  - apps/fade
  - apps/links
  - apps/reiya
  - apps/www
catalog:
  '@antfu/eslint-config': ^7.7.2
  '@astrojs/check': ^0.9.7
  '@astrojs/cloudflare': ^13.1.1
  '@astrojs/partytown': ^2.1.5
  '@astrojs/react': ^5.0.0
  '@astrojs/sitemap': ^3.7.1
  '@better-auth/passkey': ^1.5.5
  '@cloudflare/vite-plugin': ^1.28.0
  '@cloudflare/vitest-pool-workers': ^0.13.0
  '@eslint-react/eslint-plugin': ^2.13.0
  '@faker-js/faker': ^10.3.0
  '@fontsource-variable/bricolage-grotesque': ^5.2.10
  '@fontsource-variable/inter': ^5.2.8
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.2.1
  '@tanstack/devtools-vite': ^0.5.5
  '@tanstack/eslint-plugin-query': ^5.91.4
  '@tanstack/eslint-plugin-router': ^1.161.4
  '@tanstack/react-db': ^0.1.77
  '@tanstack/react-devtools': ^0.9.13
  '@tanstack/react-query': ^5.90.21
  '@tanstack/react-query-devtools': ^5.91.3
  '@tanstack/react-router': ^1.167.0
  '@tanstack/react-router-devtools': ^1.166.7
  '@tanstack/react-router-ssr-query': ^1.166.7
  '@tanstack/react-start': ^1.166.11
  '@tanstack/react-virtual': ^3.13.22
  '@tanstack/router-plugin': ^1.166.9
  '@types/better-sqlite3': ^7.6.13
  '@types/eslint-plugin-jsx-a11y': ^6.10.1
  '@types/node': ^22.19.15
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/wicg-file-system-access': ^2023.10.7
  '@typescript-eslint/eslint-plugin': ^8.57.0
  '@unpic/react': ^1.0.2
  '@vitejs/plugin-react': ^5.0.4
  '@webgpu/types': ^0.1.69
  astro: ^6.0.4
  better-auth: ^1.5.5
  better-sqlite3: ^12.8.0
  daisyui: ^5.5.19
  drizzle-kit: ^0.31.9
  drizzle-orm: ^0.45.1
  drizzle-seed: ^0.3.1
  eslint: ^9.39.4
  eslint-plugin-astro: ^1.6.0
  eslint-plugin-format: ^2.0.1
  eslint-plugin-import-lite: ^0.5.2
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.5.2
  file-type: ^21.3.2
  lightningcss: ^1.32.0
  lucide-react: ^0.577.0
  mixpanel-browser: ^2.75.0
  react: ^19.2.4
  react-dom: ^19.2.4
  sharp: ^0.34.5
  simple-icons: ^16.11.0
  tailwindcss: ^4.2.1
  tsx: ^4.21.0
  typescript: ^5.9.3
  usehooks-ts: ^3.1.1
  vite: ^7.3.1
  vitest: ^4.1.0
  web-vitals: ^5.1.0
  wrangler: ^4.73.0
  zod: ^4.3.6
catalogs:
  conflicts_@types/react-dom_h19_2_0:
    '@types/react-dom': ^19.2.0
  conflicts_@types/react_h19_2_0:
    '@types/react': ^19.2.0
  conflicts_conflicts_@types/react-dom_h19_2_0_h19_2_3:
    '@types/react-dom': ^19.2.3
  conflicts_conflicts_@types/react_h19_2_0_h19_2_7:
    '@types/react': ^19.2.7
engineStrict: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - lightningcss
  - prisma
  - sharp
  - workerd
  - wrangler
overrides:
  vite: "catalog:"
