/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as PrivacyNoticesRouteImport } from './routes/privacy-notices'
import { Route as ApiArtistsRouteImport } from './routes/api/artists'
import { Route as ApiCharactersRouteImport } from './routes/api/characters'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiMerchsRouteImport } from './routes/api/merchs'
import { Route as ApiShowcasesRouteImport } from './routes/api/showcases'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyNoticesRoute = PrivacyNoticesRouteImport.update({
  id: '/privacy-notices',
  path: '/privacy-notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtistsRoute = ApiArtistsRouteImport.update({
  id: '/api/artists',
  path: '/api/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCharactersRoute = ApiCharactersRouteImport.update({
  id: '/api/characters',
  path: '/api/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMerchsRoute = ApiMerchsRouteImport.update({
  id: '/api/merchs',
  path: '/api/merchs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShowcasesRoute = ApiShowcasesRouteImport.update({
  id: '/api/showcases',
  path: '/api/showcases',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/privacy-notices': typeof PrivacyNoticesRoute
  '/api/artists': typeof ApiArtistsRoute
  '/api/characters': typeof ApiCharactersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/merchs': typeof ApiMerchsRoute
  '/api/showcases': typeof ApiShowcasesRoute
  '/user/': typeof UserIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/privacy-notices': typeof PrivacyNoticesRoute
  '/api/artists': typeof ApiArtistsRoute
  '/api/characters': typeof ApiCharactersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/merchs': typeof ApiMerchsRoute
  '/api/showcases': typeof ApiShowcasesRoute
  '/user': typeof UserIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/privacy-notices': typeof PrivacyNoticesRoute
  '/api/artists': typeof ApiArtistsRoute
  '/api/characters': typeof ApiCharactersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/merchs': typeof ApiMerchsRoute
  '/api/showcases': typeof ApiShowcasesRoute
  '/user/': typeof UserIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/explore'
    | '/following'
    | '/privacy-notices'
    | '/api/artists'
    | '/api/characters'
    | '/api/events'
    | '/api/merchs'
    | '/api/showcases'
    | '/user/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/explore'
    | '/following'
    | '/privacy-notices'
    | '/api/artists'
    | '/api/characters'
    | '/api/events'
    | '/api/merchs'
    | '/api/showcases'
    | '/user'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/explore'
    | '/following'
    | '/privacy-notices'
    | '/api/artists'
    | '/api/characters'
    | '/api/events'
    | '/api/merchs'
    | '/api/showcases'
    | '/user/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ExploreRoute: typeof ExploreRoute
  FollowingRoute: typeof FollowingRoute
  PrivacyNoticesRoute: typeof PrivacyNoticesRoute
  ApiArtistsRoute: typeof ApiArtistsRoute
  ApiCharactersRoute: typeof ApiCharactersRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiMerchsRoute: typeof ApiMerchsRoute
  ApiShowcasesRoute: typeof ApiShowcasesRoute
  UserIndexRoute: typeof UserIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-notices': {
      id: '/privacy-notices'
      path: '/privacy-notices'
      fullPath: '/privacy-notices'
      preLoaderRoute: typeof PrivacyNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artists': {
      id: '/api/artists'
      path: '/api/artists'
      fullPath: '/api/artists'
      preLoaderRoute: typeof ApiArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/characters': {
      id: '/api/characters'
      path: '/api/characters'
      fullPath: '/api/characters'
      preLoaderRoute: typeof ApiCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/merchs': {
      id: '/api/merchs'
      path: '/api/merchs'
      fullPath: '/api/merchs'
      preLoaderRoute: typeof ApiMerchsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/showcases': {
      id: '/api/showcases'
      path: '/api/showcases'
      fullPath: '/api/showcases'
      preLoaderRoute: typeof ApiShowcasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ExploreRoute: ExploreRoute,
  FollowingRoute: FollowingRoute,
  PrivacyNoticesRoute: PrivacyNoticesRoute,
  ApiArtistsRoute: ApiArtistsRoute,
  ApiCharactersRoute: ApiCharactersRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiMerchsRoute: ApiMerchsRoute,
  ApiShowcasesRoute: ApiShowcasesRoute,
  UserIndexRoute: UserIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
